variables:
  GITLAB_CI_IMAGE_ALPINE: 'alpine:3.9'
  GITLAB_CI_IMAGE_PYTHON: 'python:3.8.6'
  GITLAB_CI_PYPI_SPHINX_RTD_THEME: 'sphinx_rtd_theme~=0.4.0'
stages:
  - build
  - deploy
docs:
  stage: build
  image: ${GITLAB_CI_IMAGE_PYTHON}
  before_script:
    - pip install "$GITLAB_CI_PYPI_SPHINX_RTD_THEME"
  script:
    - make html SPHINXOPTS="-W"
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - _build/html
pages:
  stage: deploy
  image: ${GITLAB_CI_IMAGE_ALPINE}
  script:
    - mv _build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - stable
